artifacts_config:
  artifacts_dir: artifacts

data_ingestion_config:
  dataset_download_url: "https://github.com/Ajit171098/Kaggle-datasets/raw/refs/heads/main/Books_DataSet.zip"
  dataset_dir: dataset
  ingested_dir: ingested
  raw_data_dir: raw_data

data_validation_config:
  clean_data_dir: "clean_data"
  serialized_object_dir: serialized_object
  books_csv_file: "Books.csv"
  ratings_csv_file: "Ratings.csv"

data_transformation_config:
  transformed_data_dir: "transformed_data"

model_trainer_config:
  trained_model_dir: "trained_model"
  model_file_name: "model.pkl"