artifacts_config:
  artifacts_dir: artifacts

data_ingestion_config:
  dataset_download_url: "https://github.com/Ajit171098/Kaggle-datasets/raw/refs/heads/main/Books_DataSet.zip"
  dataset_dir: dataset
  ingested_dir: ingested
  raw_data_dir: raw_data